# Generated by Django 5.1.3 on 2024-11-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_end",
            field=models.DateTimeField(verbose_name="Время окончания отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_start",
            field=models.DateTimeField(verbose_name="Время отправки"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="mailing_service.message",
                verbose_name="Письмо",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                max_length=9,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="user_mail",
            field=models.ManyToManyField(
                related_name="users",
                to="mailing_service.usermail",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailing_attempts",
                to="mailing_service.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Success", "Успешно"), ("Not successful", "Не успешно")],
                max_length=14,
                verbose_name="Статус",
            ),
        ),
    ]
