# Generated by Django 5.1.3 on 2024-11-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0002_alter_mailing_date_end_alter_mailing_date_start_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                ],
                default="Создана",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
    ]
