# Generated by Django 5.1.3 on 2024-11-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="date_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="date_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время отправки"
            ),
        ),
    ]
