# Generated by Django 5.1.3 on 2024-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_service",
            "0003_mailing_owner_mailingattempt_owner_message_owner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingattempt",
            options={
                "ordering": ["datetime_attempt", "status", "mail_response", "mailing"],
                "permissions": [("can_ban_user", "can ban user")],
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailingattempt",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=14,
                verbose_name="Статус",
            ),
        ),
    ]
